name: pacsman_data
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter==1.0.0
  - dcm2niix=1.0.20230411
  - pip :
    - dicom-parser==1.2.3
    - pydicom==2.3.1
    - nilearn==0.10.2
    - nibabel==5.2.0
    - matplotlib==3.8.2
